# This file was auto-generated by Fern from our API Definition.

import typing

from .return_back_to_user_error_response import ReturnBackToUserErrorResponse

ReturnBackToUserUnionType = typing.Union[ReturnBackToUserErrorResponse, typing.Dict[str, typing.Any]]
